### ISSUE TITLE
Profile: UI for validating a Federal email address

### ISSUE THREAD

**Issue by humancompanion** [USAJOBS/team-titan#1059]
* [x] Consider moving Federal email address from Contact Info to Federal service.
* [x] Create an interface for showing the state of email validation.
* [x] Create an interface to trigger email validation.
* [x] Content for the validation email.
* [ ] Content and alert treatment for the profile dashboard (or profile) reminder to validate that email (do we really need this?)

**Comment by humancompanion** [comment]
@dalenard21 - This is the message we had for secondary account validation:

```
Hello [[GivenName]],    We’ve received your request to add this email address, as your secondary email address, to your USAJOBS account.  Please click the link below to verify your secondary email address: [[URLLink]]  
```

So I'd propose:
```
Hello [[GivenName]],    

We’ve received your request to add this email address, as your Federal government email address, to your USAJOBS account.  Please click the link below to verify your Federal government email address: [[URLLink]]

We'll only use this address with other systems that require a Federal email for their use. 
```

I could use some help on this email content. 

I don't think we need an alert treatment. I'm just showing the unconfirmed status inline: http://usajobs.github.io/american-discovery-trail/profile/v2/incomplete/

**Comment by humancompanion** [comment]
## Draft requirements

1. Create "Federal Government email address" in the Experience > Federal service section of Profile.
  * Should appear after Department & Agency and before Service.
2. When a Fed email is unverified a link with the text "Please confirm this email address" preceded by a red, X icon appears below the email address.
  * This link is a permalink (even if the user has visited this link it should appear blue).
  * Clicking this link anchors the user to the Federal Government email address label. The " I am currently a federal civilian employee." option would be selected and thus all fields under "Current federal service" would be displayed.
 3. When a Fed email is unverified on the Federal service page the following link would appear below the input field: "Confirm this email address". This link text is preceded by a small, red email envelope icon.
  * This link is a permalink (even if the user has visited this link it should appear blue).
  * Clicking the link changes the icon and text to green and updates the text to read "Confirmation email sent. Check your inbox (and possibly your spam folder)". The text update is animated (see https://github.com/USAJOBS/american-discovery-trail/blob/gh-pages/js/components/profile-form.js#L92)

**Comment by dalenard21** [comment]
@humancompanion here's my take on the email language. I changed it a bit.

"Hello [[GivenName]],    

You recently updated your USAJOBS profile to include this email address as your Federal Government email address. Please click the link below to confirm this is your Federal Government email address.

 [[URLLink]]

We'll only use this email address to verify you’re a current federal employee when using government sites that require a Federal Government email address."

Do you think we even need the "...when using government sites that require a Federal Government email address".  ?  Do you think we can just leave it as "We'll only use this email address to verify you're a current federal employee."?

**Comment by humancompanion** [comment]
@dalenard21 - Yes, I think we could leave it out. Thanks. I'll pass this onto John.
