### ISSUE TITLE
Open Opps terms and conditions.

### ISSUE THREAD

**Issue by yraza261** [USAJOBS/team-titan#1090]
- Get Open Opps approved by Victor
- Get correct URL to terms and conditions

**Comment by humancompanion** [comment]
@dalenard21 and @Piglady64 to gather the content. Create a Word doc and hand it to Brice and co. We don't feel comfortable posting this to github as it isn't a .gov domain.

**Comment by dalenard21** [comment]
Can we move this to the Open Opps board?

**Comment by humancompanion** [comment]
This is a duplicate of https://github.com/openopps/OpenOppsTasks/issues/105
