### ISSUE TITLE
Re-test create new user flow

### ISSUE THREAD

**Issue by yraza261** [USAJOBS/team-titan#1093]
Recommendation is to allow Open Opps to inform where users should go when they come from Core. 

- When coming from Open Opps, display info (ex:modal/text/blue page?) about why they are being sent to USAJOBS

**Comment by humancompanion** [comment]
At what point are we showing a transition screen for Open Opps users? I can't take action on this until I understand what the request is.

**Comment by kbwagner** [comment]
@humancompanion I can't get into test to try this today and confirm but really the only transition screen is the login.gov screen.  Otherwise we don't really tell the user they are moving between the two systems.

**Comment by humancompanion** [comment]
@kbwagner - Is it possible to test the new user flow for users starting in Open Opps in our staging environment yet?

**Comment by kbwagner** [comment]
@humancompanion this can be tested in the test environment now https://openopps.test.usajobs.gov.  UAT will be updated next week and then it can be tested there as well.

**Comment by abudz19** [comment]
<img width="997" alt="USAJOBS" src="https://user-images.githubusercontent.com/11526811/55099335-e4c55e80-5095-11e9-852f-b02e6ba31f8e.png">
I got this in test after creating a new login account and trying to sign in afterward.

**Comment by abudz19** [comment]
Clicking back brought me here, but there is nothing telling me to go back to Open Opps after I fill out my profile. (chrome)
<img width="1356" alt="USAJOBS_-_Profile_Dashboard" src="https://user-images.githubusercontent.com/11526811/55099516-3968d980-5096-11e9-8099-2f735fab5d67.png">

**Comment by Piglady64** [comment]
I had the same trouble last week. I had to go in and clear my cookies. This is an akimi (not spelled right) message that comes from USAJOBS and Brice couldn’t figure out why I was getting it. Clear your cookies and try to sign in again. Mine finally started working last week and now Katrina is having trouble.

Julie Jackson
Usability Test Lead
USAJOBS

P: 202-606-5230 | M: 202-718-7608
Julie.Jackson@opm.gov<mailto:Julie.Jackson@opm.gov> | www.opm.gov/HRS<http://www.opm.gov/HRS>
[USAJOBS]<https://www.usajobs.gov/>
[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/usajobs> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/c/usajobs>

**Comment by Piglady64** [comment]
We know about the back button issue. Debbie brought that up yesterday.


Julie Jackson
Usability Test Lead
USAJOBS

P: 202-606-5230 | M: 202-718-7608
Julie.Jackson@opm.gov<mailto:Julie.Jackson@opm.gov> | www.opm.gov/HRS<http://www.opm.gov/HRS>
[USAJOBS]<https://www.usajobs.gov/>
[usajobs-facebook-s]<https://www.facebook.com/USAJOBS>[usajobs-twitter-s]<https://twitter.com/usajobs> [usajobs-linkedin-s] <https://www.linkedin.com/company/usajobs>  [usajobs-youtube-s] <https://www.youtube.com/c/usajobs>

**Comment by abudz19** [comment]
@humancompanion Considering the expected changes to the blue screen mentioned as the impetus for this ticket, can this be closed? Other than hitting the known blocker that was the blue screen, the new user process worked fine during testing yesterday.

**Comment by abudz19** [comment]
Will create a new issue to re-test user flow when replacement for blue screen is deployed.
