### ISSUE TITLE
Email: Change to federal email address field

### ISSUE THREAD

**Issue by dalenard21** [USAJOBS/team-titan#1109]
**Type:** Task

**Timeline:** asap

-----

**Description**

We need an email to explain to users the change in the federal email address field.  From now on that field is unique and a you cannot use the same federal email address on multiple accounts.  If we find a federal email address on multiple account we will keep it on the most recently used account and remove it from the others.  This email will explain that to users.   Can you take a look and edit as needed?  Thanks

Dear [firstname]

You have been identified as an owner of multiple USAJOBS accounts that make use of the new Federal email address field located in the profile.  This is a notice to inform you that we have updated the requirements for the use of the federal email address field.  Moving forward a single federal email address can only be used on one USAJOBS account and cannot be duplicated across different accounts.

The USAJOBS account connected to this email address [email address] will retain the federal email address of [federal email address].    The federal email address will be removed from your other USAJOBS accounts.

This update will not affect your ability to apply for positions.  If you have any questions or concerns please contact us. (edited)

**Comment by dalenard21** [comment]
@Piglady64 - can you do a quick review of this new email?  See above for the 'requirement' from John.

Suggested content update:

Hello [GivenName]
We’re emailing you, because you currently have multiple USAJOBS profiles using the same federal email address and we’re changing the rules for the federal email address field. 

Moving forward, you can only use your federal email address with **one** USAJOBS profile. You can no longer use the same federal email address across multiple profiles.

We’ll keep your federal email address of [federal email address] with the profile connected to this email address [email address]. However, we will remove the federal email address from your other USAJOBS profiles.

This change does not affect any job(s) that you’ve already applied to, nor will it affect your ability to apply to new jobs.

If you have any questions or concerns, please contact us. 

Thanks,
The USAJOBS Team

**Comment by Piglady64** [comment]
@dalenard21 I have added some comments. This email is really confusing. It states the same thing in different ways but still doesn't tell me which profile my email is staying on. 
[federal email address email_Core.docx](https://github.com/USAJOBS/team-titan/files/3010199/federal.email.address.email_Core.docx)

**Comment by dalenard21** [comment]
Here's the content I sent to John to use.

[USAJOBS-email-federal-gov-email-address-update_v2_20190327.docx](https://github.com/USAJOBS/team-titan/files/3014344/USAJOBS-email-federal-gov-email-address-update_v2_20190327.docx)

**Comment by dalenard21** [comment]
Issue closed.
