### ISSUE TITLE
Fix blue bar itis

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#19]
This is where Tim saves us from giant, blue bars spread across every page of our site. 

**Old Trello URL:** https://trello.com/c/inZ8Sufs/1226-fix-blue-bar-itis

**Checklists:**

**Attachments:** 

**Comments:**

*Matthew Dingee 2018-07-20*: Tim & I to go through systematically and define reasons for using particular shades of blue throughout.

**Comment by humancompanion** [comment]
Moved to team-design: https://github.com/USAJOBS/team-design/issues/1

I can't see team-titan caring about this.
