### ISSUE TITLE
Profile: Find or Create Profile

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#28]
Iterate on the post-login.gov screen.

**Old Trello URL:** https://trello.com/c/gJTyzB9b/1216-profile-find-or-create-profile

**Checklists:**

**Attachments:** 

**Comments:**

*Matthew Dingee 2018-07-20*: Tim and Min to focus on this for Open Opps and determine if any visual design changes need to be made.

*Tim Vienckowski 2018-06-22*: @matthewdingee1 https://opm.invisionapp.com/d/main/#/console/14031834/293328879/preview 

This is the screen that I know of.

*Matthew Dingee 2018-06-11*: Anything to report here? Did you all get together to discuss this last week?

**Comment by humancompanion** [comment]
This work has been done.
