### ISSUE TITLE
Profile: Test on-boarding

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#46]
**Old Trello URL:** https://trello.com/c/UELBIKAd/1212-profile-test-on-boarding

**Checklists:**

**Attachments:** 

**Comments:**

*Julie Jackson 2018-06-05*: @matthewdingee1 I will be in the Lab's Summer Design School the on the 19th so we will have to plan to test the following week. When you get back let's sit down and figure out who we want to test and when so I can at least reserve a spot or start recruiting.

**Comment by humancompanion** [comment]
We did this in September.
