### ISSUE TITLE
Profile: What would you like to do next screen?

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#53]
I'd like to explore a screen post-data collection but pre-home that could handle putting users on different paths depending on where they are in their journey. This would allow us to signal what is important as well as measure that paths users are interested in. 

What would you like to do next?

#### For most paths the options could be:
1. Apply to a job I've already found
2. Find a job
3. Learn more about the differences between jobs in the public vs. private sectors
4. Find a micro-detail opportunity

#### For Students & Recent grads it could be
1. Find an internship
2. Find a job open to recent graduates
3. Learn more about what the government has to offer

**Old Trello URL:** https://trello.com/c/zcNPJU3G/1169-profile-what-would-you-like-to-do-next-screen

**Checklists:**

**Attachments:** 

[Screenshot 2018-04-16 17.43.53.png](https://trello-attachments.s3.amazonaws.com/5623ffeeee531d25521a97ba/5ad5f7ceb0f5d6ad7bee039e/b53b28f191949d2c104195ae4bfabb4c/Screenshot_2018-04-16_17.43.53.png)

**Comments:**

*Matthew Dingee 2018-06-25*: https://opm.invisionapp.com/d/main/#/console/14031834/293328879/preview

**Comment by humancompanion** [comment]
I need to prototype this page at the end of the new user onboarding flow.

**Comment by humancompanion** [comment]
I've created a few variations which we'll test out next week. @timtimtimtimofficial created the Open Opps alt of Profile dashboard.
