### ISSUE TITLE
Profile/New user flow: Prototype new user flow

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#54]
Dev would prefer that I prototype on-boarding in code to help speed things along. I'd eventually like to have an end-to-end experience prototyped. Thus I'm going to start here and then borrow dev's code for the Profile. Eventually I hope to move this to a Rails prototype deployed to cloud.gov.

**Old Trello URL:** https://trello.com/c/q7HEjyje/1198-profile-prototype-on-boarding

### Prototype for testing
* [x] Complete forms
* [x] Add Profile forms - prioritize Federal service
* [x] Deploy to cloud.gov

List of outstanding sub-issues as I go:
#### Complete forms
* [x] Finish hiring paths
  * [x] Add more margin between sections on hiring paths confirm
* [x] Revise how this works styling
* [x] Finish Contact info (add telephone type)
* [x] Finish citizenship
* [x] Create work experience
* [x] Create Fed experience
  * [x] Fix series to return code + name
  * [ ] JS to flip between current and former
* [x] Create Vet experience
* [x] Create Fed + Vet experience
* [x] Create Education
* [x] Create jobs to be done final page + congrats msg
* [x] Add edit previous sections to top of steps 2 and 3
* [x] Seeding a new user
* [x] Validations working correctly
* [x] Add numbers to design system and then to form steps

#### Add Profile forms
* [x] Profile index
* [x] Add modal to start test (let's complete your profile)
* [x] Federal service
* [x] Military service
* [ ] Work experience
* [x] Education
* [x] Hiring paths
* [x] Contact info
* [x] Citizenship
* [ ] Organizations
* [ ] References
* [ ] Languages

#### Deploy to cloud.gov
* [x] Verify migrations are set (all fields present)
* [x] Remove jobs from seeds to speed up db setup
* [x] Deploy

### Enhancements 
   - [ ] Employ goal gradient effect, which affirms that motivation increases the closer we are to completing our goals, by starting the progress bar partially full (users have completed the hiring paths questions before the progress bar appears)
   - [ ] Code form to have contact information pre-populated from the browser
   - [ ] What rewards can we offer early on in the process? (Allow us to filter jobs for you, the basics from the landing page, etc.)
   - [ ] Can we make it a one-pager and add some animation?

These are all stretch goals at this point.

**Comment by humancompanion** [comment]
### Improvements post-usability test
* [x] Hiring paths confirmation - Switch to two columns for paths not selected at ML breakpoint.
* [ ] Next steps - Bring Finish Profile to the top
* [ ] Next steps - Put notifications in the list
* [ ] Next steps - Only show Learn a skill to Feds (left out for launch) 
* [ ] Next steps - Rename Learn a skill to Develop a skill
* [ ] Next steps - Fix start your search button in find a job.
* [x] Turn U.S. State/Territory/Province into a normal select menu (drop select2)
* [ ] Re-style the select2 plugin: focus, placeholder text
* [ ] Add help text below select2 plugin dropdowns to note 
* [ ] Default to U.S. Citizen us on Citizenship page if U.S. Citizen selected from hiring paths
* [x] Change language in hiring paths select to use "all of the groups that apply"
* [x] Hring paths select - make select all that apply bigger
* [x] Summary page - switch time estimate to 3-5 minutes from 10-15 minutes


### Preparing for next week's Education test
* [ ] Add Dates to Education

### For later (week of 8/20)
* [ ] Rename "How is working in the federal government different than the private sector" to "How is finding a job in the federal government different than in the private sector"
* [ ] Add Fed + Students, Fed + Vet + Students paths

### Open questions
* Add a review step?
* Is autocomplete superior to the select2 plugin? Let's A/B test them then switch all fields that require either to the same treatment (potentially).
* Learn/Develop a new skill isn't working. Participants were interested but, Open Opps is not what they were expecting (looking for coursework, training, webinars, etc.). Intrigued by Open Opps but, we need to do a better job explaining it (Develop a new skill via micro-details?)
* Once we have Hiring paths, agencies, and grade(s) in search preferences perhaps setting those up or a quick "add everything you just told us about to search prefs" box in next steps would be appropriate.
* Heard from one user the desire to have jobs recommended to him based on keywords or skills. Is there an MVP here of a next step that encourages users to upload a resume then uses elastic to find top keywords and then allows the user to quickly compose a search based on everything they provided?

**Comment by humancompanion** [comment]
All pending items have been turned into distinct issues. Closing.
