### ISSUE TITLE
Profile: On-board path for non-U.S. Citizens (None of these apply)

### ISSUE THREAD

**Issue by sean-lewis** [USAJOBS/team-titan#55]
If the user answers "None of these apply" to the "Tell us who you are" screen then the presumption is that they are a non-U.S. Citizen. So we'll confirm that on the confirmation page that follows and then their version of the Citizenship screen would already have Are you a U.S. Citizen set to No thus revealing the pull down menu. 

We need to depict this flow.

**Old Trello URL:** https://trello.com/c/rPOphjCC/1176-profile-on-board-path-for-non-us-citizens-none-of-these-apply

**Checklists:**

**Attachments:** 

**Comments:**

*Matthew Dingee 2018-05-15*: This is a part of on-boarding so I will roll this into that work.

**Comment by humancompanion** [comment]
This was done, poorly, but at least it got done. I asked the design team to file 3 backlog items to correct the poor behavior.
